source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.8'
# Use postgresql as the database for Active Record
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

# Client-servier communication over websockets

gem 'eventmachine'
gem 'eventmachine_httpserver'

gem 'httparty'
gem 'websocket-eventmachine-server'
gem 'json'

# Bootstrap

gem 'bootstrap3-rails'

# Graphs

gem 'flot-rails'

# User modeling

gem 'devise'

# Vehicle connector server control

gem 'god'

# Vehicle connector client testing

gem 'faye-websocket', group: [:development, :test]

# Deployment

group :development do
  gem 'capistrano', '~> 3.3.3'
  gem 'capistrano-rbenv', '~> 2.0'
  gem 'capistrano-rbenv-install', '~> 1.2.0'
  gem 'capistrano-rails', '~> 1.1'
  gem 'capistrano-passenger'
  gem 'capistrano-secrets-yml'
end

# Production

group :production do
  gem 'passenger'
end

# Unit and acceptance testing

group :test do
  gem 'minitest'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'cucumber-rails', require: false
  gem 'database_cleaner'
  gem 'ci_reporter_minitest'
  gem 'ci_reporter_cucumber'
  gem 'factory_girl_rails'
end

# Use debugger
# gem 'debugger', group: [:development, :test]

